sudo: required
dist: bionic
group: edge

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-qmake qtbase5-dev qt5-default qttools5-dev-tools libqt5serialport5-dev libqt5webkit5-dev
  - sudo apt-get install -qq zlib1g-dev libudev-dev

language: cpp

# Compiler selection
compiler:
  - gcc

install: true

# Build steps
script:
  - make all
